apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namePrefix: local--

resources:
  - ../../base

#patches:
#  - patch: |-
#      - op: replace
#        path: /spec/template/spec/containers/0/env/2/value
#        value: "changeme"
#    target:
#      kind: Deployment
#      name: postgres-deployment
